apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstack2-pv
spec:
  capacity: 
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/localstack2
